# Generated by Django 5.2.6 on 2025-10-13 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email utilizado en el intento de login', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP del usuario')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador', null=True)),
                ('error_type', models.CharField(blank=True, choices=[('user_not_found', 'Usuario no existe'), ('wrong_password', 'Contraseña incorrecta'), ('invalid_email', 'Email inválido'), ('account_disabled', 'Cuenta deshabilitada'), ('too_many_attempts', 'Demasiados intentos'), ('ip_blocked', 'IP bloqueada'), ('network_error', 'Error de red'), ('server_error', 'Error del servidor'), ('invalid_token', 'Token inválido'), ('expired_token', 'Token expirado'), ('missing_credentials', 'Credenciales faltantes'), ('weak_password', 'Contraseña muy débil'), ('email_not_verified', 'Email no verificado'), ('account_locked', 'Cuenta bloqueada'), ('other', 'Otro error')], help_text='Tipo de error de autenticación', max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error detallado', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del intento')),
                ('success', models.BooleanField(default=False, help_text='Indica si el intento fue exitoso')),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión del usuario', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Log de Autenticación',
                'verbose_name_plural': 'Logs de Autenticación',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'timestamp'], name='usuarios_au_email_006e6a_idx'), models.Index(fields=['ip_address', 'timestamp'], name='usuarios_au_ip_addr_0df26b_idx'), models.Index(fields=['success', 'timestamp'], name='usuarios_au_success_530bbf_idx')],
            },
        ),
    ]
