# Generated by Django 5.2.6 on 2025-10-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationlog',
            name='error_type',
            field=models.CharField(blank=True, choices=[('user_not_found', 'Usuario no existe'), ('wrong_password', 'Contraseña incorrecta'), ('invalid_email', 'Email inválido'), ('invalid_credential', 'Credenciales incorrectas'), ('account_disabled', 'Cuenta deshabilitada'), ('too_many_attempts', 'Demasiados intentos'), ('ip_blocked', 'IP bloqueada'), ('network_error', 'Error de red'), ('server_error', 'Error del servidor'), ('invalid_token', 'Token inválido'), ('expired_token', 'Token expirado'), ('missing_credentials', 'Credenciales faltantes'), ('weak_password', 'Contraseña muy débil'), ('email_not_verified', 'Email no verificado'), ('account_locked', 'Cuenta bloqueada'), ('inactivity_logout', 'Logout por inactividad'), ('other', 'Otro error')], help_text='Tipo de error de autenticación', max_length=20, null=True),
        ),
    ]
